// Generated by CoffeeScript 1.6.3
var alphabetSoup, coinDeterminer, vowelCount,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

alphabetSoup = function(str) {
  var charArray;
  charArray = str.split("");
  return charArray.sort().join("");
};

vowelCount = function(str) {
  var charArray, count, item, vowels, _i, _len, _ref;
  vowels = ["a", "e", "i", "o", "u"];
  count = 0;
  charArray = str.split("");
  for (_i = 0, _len = charArray.length; _i < _len; _i++) {
    item = charArray[_i];
    if (_ref = item.toLowerCase(), __indexOf.call(vowels, _ref) >= 0) {
      count++;
    }
  }
  return count;
};

coinDeterminer = function(num) {
  var coinTotal, div, divArray, factor, numCopy, _i;
  divArray = [1, 5, 7, 9, 11];
  coinTotal = 0;
  numCopy = num;
  for (_i = divArray.length - 1; _i >= 0; _i += -1) {
    div = divArray[_i];
    if (numCopy / div >= 1) {
      factor = Math.floor(numCopy / div);
      coinTotal += factor;
      numCopy += -(div * factor);
    }
    console.log(numCopy, div);
  }
  return coinTotal;
};
